/**
 * Google Gemini Provider Implementation
 * Phase AI-3: Gemini Integration
 * 
 * Provides real AI responses using Google's Gemini API.
 * Integrates with the existing provider factory architecture.
 */

import { GoogleGenerativeAI } from '@google/generative-ai';
import { env } from '../../../config/env.js';

/**
 * Response interface matching the provider factory contract
 */
export interface GeminiProviderResponse {
  answer: string;
  raw?: unknown;
  metadata?: {
    model: string;
    provider: 'gemini';
    promptTokens?: number;
    completionTokens?: number;
    totalTokens?: number;
    latencyMs?: number;
  };
}

/**
 * Options for Gemini requests
 */
export interface GeminiOptions {
  temperature?: number;
  maxTokens?: number;
  timeout?: number;
}

/**
 * System prompt for ITSM context
 */
const SYSTEM_PROMPT = `You are an AI assistant for Saven InfraOps Command Center, an enterprise ITSM (IT Service Management) platform.

Your capabilities:
- Answer questions about service requests, incidents, assets, compliance, and access management
- Provide summaries of open tickets and their priorities
- Help users navigate the platform and understand ITSM workflows
- Explain ITSM concepts and best practices (ITIL framework)
- Assist with troubleshooting common IT issues

Guidelines:
- Be concise and helpful in your responses
- When providing counts or summaries, mention the data source
- If you don't know something, say so clearly
- Focus on actionable information
- Use professional tone appropriate for enterprise IT environments

Current date: ${new Date().toISOString().split('T')[0]}`;

/**
 * Execute a Gemini content generation request
 * 
 * @param question - The user's question
 * @param options - Optional configuration (temperature, maxTokens, timeout)
 * @returns GeminiProviderResponse with answer and metadata
 */
export async function runGemini(
  question: string,
  options?: GeminiOptions
): Promise<GeminiProviderResponse> {
  const modelName = env.GEMINI_MODEL || 'gemini-1.5-flash';
  const temperature = options?.temperature ?? env.GEMINI_TEMPERATURE ?? 0.7;
  const maxTokens = options?.maxTokens ?? env.GEMINI_MAX_TOKENS ?? 2048;
  const timeout = options?.timeout ?? env.GEMINI_TIMEOUT ?? 30000; // 30 second default timeout

  // Validate API key
  if (!env.GEMINI_API_KEY) {
    return {
      answer: 'Gemini provider is selected but GEMINI_API_KEY is not configured. Please set the GEMINI_API_KEY environment variable.',
      metadata: {
        model: modelName,
        provider: 'gemini',
      },
    };
  }

  // Initialize Gemini client
  const genAI = new GoogleGenerativeAI(env.GEMINI_API_KEY);

  // Get model with generation config
  const model = genAI.getGenerativeModel({
    model: modelName,
    generationConfig: {
      temperature,
      maxOutputTokens: maxTokens,
      topP: 0.9,
      topK: 40,
    },
  });

  const startTime = Date.now();

  try {
    // Build prompt with system context
    const prompt = `${SYSTEM_PROMPT}

User question: ${question}

Please provide a helpful response based on your role as an ITSM assistant.`;

    // Generate content
    const result = await model.generateContent(prompt);
    const response = result.response;
    
    const latencyMs = Date.now() - startTime;

    // Extract response text
    const answer = response.text() || 'No response generated by Gemini.';

    // Get token usage if available
    const usageMetadata = response.usageMetadata;

    return {
      answer,
      raw: response,
      metadata: {
        model: modelName,
        provider: 'gemini',
        promptTokens: usageMetadata?.promptTokenCount,
        completionTokens: usageMetadata?.candidatesTokenCount,
        totalTokens: usageMetadata?.totalTokenCount,
        latencyMs,
      },
    };
  } catch (error) {
    const latencyMs = Date.now() - startTime;

    // Handle specific Gemini errors
    if (error instanceof Error) {
      console.error(`[Gemini] Error: ${error.message}`);
      
      // Provide user-friendly error messages based on error type
      if (error.message.includes('API_KEY_INVALID') || error.message.includes('api key')) {
        return {
          answer: 'Gemini authentication failed. Please check your GEMINI_API_KEY is valid.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (error.message.includes('quota') || error.message.includes('rate limit') || error.message.includes('429')) {
        return {
          answer: 'Gemini quota exceeded. Please wait a moment and try again.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (error.message.includes('resource has been exhausted') || error.message.includes('out of memory')) {
        return {
          answer: 'Gemini resources exhausted. Please try again with a shorter question.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (error.message.includes('DEADLINE_EXCEEDED') || error.message.includes('timeout')) {
        return {
          answer: 'Gemini request timed out. Please try again or use a simpler question.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (error.message.includes('service unavailable') || error.message.includes('503')) {
        return {
          answer: 'Gemini service is currently unavailable. Please try again later.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (error.message.includes('blocked') || error.message.includes('safety')) {
        return {
          answer: 'Gemini blocked this request due to safety settings. Please rephrase your question.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }

      return {
        answer: `Gemini error: ${error.message}`,
        metadata: { model: modelName, provider: 'gemini', latencyMs },
      };
    }

    // Handle unknown errors
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error(`[Gemini] Unexpected error: ${errorMessage}`);

    return {
      answer: `Gemini request failed: ${errorMessage}`,
      metadata: { model: modelName, provider: 'gemini', latencyMs },
    };
  }
}

/**
 * Validate Gemini configuration
 * Returns true if Gemini is properly configured
 */
export function isGeminiConfigured(): boolean {
  return Boolean(env.GEMINI_API_KEY && env.AI_PROVIDER === 'gemini');
}
