/**
 * Google Gemini Provider Implementation
 * Phase AI-3: Gemini Integration (Updated for Gemini 2.0 API)
 * 
 * Provides real AI responses using Google's Gemini API.
 * Uses the new @google/genai SDK with gemini-2.0-flash model.
 * Integrates with the existing provider factory architecture.
 */

import { GoogleGenAI, createPartFromText } from '@google/genai';
import { env } from '../../../config/env.js';

/**
 * Response interface matching the provider factory contract
 */
export interface GeminiProviderResponse {
  answer: string;
  raw?: unknown;
  metadata?: {
    model: string;
    provider: 'gemini';
    promptTokens?: number;
    completionTokens?: number;
    totalTokens?: number;
    latencyMs?: number;
  };
}

/**
 * Options for Gemini requests
 */
export interface GeminiOptions {
  temperature?: number;
  maxTokens?: number;
}

/**
 * System prompt for ITSM context
 */
const SYSTEM_PROMPT = `You are an AI assistant for Saven InfraOps Command Center, an enterprise ITSM (IT Service Management) platform.

Your capabilities:
- Answer questions about service requests, incidents, assets, compliance, and access management
- Provide summaries of open tickets and their priorities
- Help users navigate the platform and understand ITSM workflows
- Explain ITSM concepts and best practices (ITIL framework)
- Assist with troubleshooting common IT issues

Guidelines:
- Be concise and helpful in your responses
- When providing counts or summaries, mention the data source
- If you don't know something, say so clearly
- Focus on actionable information
- Use professional tone appropriate for enterprise IT environments

Current date: ${new Date().toISOString().split('T')[0]}`;

/**
 * Execute a Gemini content generation request
 * 
 * @param question - The user's question
 * @param options - Optional configuration (temperature, maxTokens)
 * @returns GeminiProviderResponse with answer and metadata
 */
export async function runGemini(
  question: string,
  options?: GeminiOptions
): Promise<GeminiProviderResponse> {
  // Use gemini-2.0-flash as the default model (free tier available)
  const modelName = env.GEMINI_MODEL || 'gemini-2.0-flash';
  const temperature = options?.temperature ?? env.GEMINI_TEMPERATURE ?? 0.7;
  const maxTokens = options?.maxTokens ?? env.GEMINI_MAX_TOKENS ?? 2048;

  // Validate API key
  if (!env.GEMINI_API_KEY) {
    return {
      answer: 'Gemini provider is selected but GEMINI_API_KEY is not configured. Please set the GEMINI_API_KEY environment variable.',
      metadata: {
        model: modelName,
        provider: 'gemini',
      },
    };
  }

  // Initialize new Gemini client
  const genAI = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY! });

  const startTime = Date.now();

  try {
    // Build prompt with system context
    const prompt = `${SYSTEM_PROMPT}

User question: ${question}

Please provide a helpful response based on your role as an ITSM assistant.`;

    // Generate content using the new SDK
    const response = await genAI.models.generateContent({
      model: modelName,
      contents: [{ role: 'user', parts: [createPartFromText(prompt)] }],
      config: {
        temperature,
        maxOutputTokens: maxTokens,
      },
    });

    const latencyMs = Date.now() - startTime;

    // Extract response text
    const text = response.candidates?.[0]?.content?.parts?.[0]?.text;
    const answer = text || 'No response generated by Gemini.';

    // Get token usage if available
    const usageMetadata = response.usageMetadata;

    return {
      answer,
      raw: response,
      metadata: {
        model: modelName,
        provider: 'gemini',
        promptTokens: usageMetadata?.promptTokenCount,
        completionTokens: usageMetadata?.candidatesTokenCount,
        totalTokens: usageMetadata?.totalTokenCount,
        latencyMs,
      },
    };
  } catch (error) {
    const latencyMs = Date.now() - startTime;
    
    // DEBUG: Log full error object
    console.error('[Gemini] RAW ERROR OBJECT:');
    console.error(JSON.stringify(error, null, 2));
    
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';

    // Handle specific Gemini errors
    if (error instanceof Error) {
      console.error(`[Gemini] Parsed Error Message: ${errorMessage}`);
      console.error(`[Gemini] Error Name: ${error.name}`);
      console.error(`[Gemini] Error Stack: ${error.stack}`);
      
      // Provide user-friendly error messages based on error type
      if (errorMessage.includes('API_KEY_INVALID') || 
          errorMessage.includes('api key') || 
          errorMessage.includes('401')) {
        return {
          answer: 'Gemini authentication failed. Please check your GEMINI_API_KEY is valid.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (errorMessage.includes('quota') || 
          errorMessage.includes('rate limit') || 
          errorMessage.includes('429') ||
          errorMessage.includes('RESOURCE_EXHAUSTED')) {
        return {
          answer: 'Gemini quota exceeded. Please wait a moment and try again.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (errorMessage.includes('DEADLINE_EXCEEDED') || 
          errorMessage.includes('timeout') ||
          errorMessage.includes('timed out')) {
        return {
          answer: 'Gemini request timed out. Please try again or use a simpler question.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (errorMessage.includes('service unavailable') || 
          errorMessage.includes('503') ||
          errorMessage.includes('UNAVAILABLE')) {
        return {
          answer: 'Gemini service is currently unavailable. Please try again later.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }
      
      if (errorMessage.includes('blocked') || 
          errorMessage.includes('safety') ||
          errorMessage.includes('SAFETY')) {
        return {
          answer: 'Gemini blocked this request due to safety settings. Please rephrase your question.',
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }

      if (errorMessage.includes('not found') || errorMessage.includes('MODEL_NOT_FOUND')) {
        return {
          answer: `Gemini model '${modelName}' not found. Please check GEMINI_MODEL is correct.`,
          metadata: { model: modelName, provider: 'gemini', latencyMs },
        };
      }

      return {
        answer: `Gemini error: ${errorMessage}`,
        metadata: { model: modelName, provider: 'gemini', latencyMs },
      };
    }

    // Handle unknown errors
    console.error(`[Gemini] Unexpected error: ${errorMessage}`);

    return {
      answer: `Gemini request failed: ${errorMessage}`,
      metadata: { model: modelName, provider: 'gemini', latencyMs },
    };
  }
}

/**
 * Validate Gemini configuration
 * Returns true if Gemini is properly configured
 */
export function isGeminiConfigured(): boolean {
  return Boolean(env.GEMINI_API_KEY && env.AI_PROVIDER === 'gemini');
}
