/**
 * OpenAI Provider Implementation
 * Phase AI-1: OpenAI Integration
 * 
 * Provides real AI responses using OpenAI's Chat Completions API.
 * Integrates with the existing provider factory architecture.
 */

import OpenAI from 'openai';
import { env } from '../../../config/env.js';

/**
 * Response interface matching the provider factory contract
 */
export interface AiProviderResponse {
  answer: string;
  raw?: unknown;
  metadata?: {
    model: string;
    provider: 'openai';
    promptTokens?: number;
    completionTokens?: number;
    totalTokens?: number;
    latencyMs?: number;
  };
}

/**
 * Options for OpenAI requests
 */
export interface OpenAiOptions {
  temperature?: number;
  maxTokens?: number;
  timeout?: number;
}

/**
 * System prompt for ITSM context
 */
const SYSTEM_PROMPT = `You are an AI assistant for Saven InfraOps Command Center, an enterprise ITSM (IT Service Management) platform.

Your capabilities:
- Answer questions about service requests, incidents, assets, compliance, and access management
- Provide summaries of open tickets and their priorities
- Help users navigate the platform and understand ITSM workflows
- Explain ITSM concepts and best practices (ITIL framework)
- Assist with troubleshooting common IT issues

Guidelines:
- Be concise and helpful in your responses
- When providing counts or summaries, mention the data source
- If you don't know something, say so clearly
- Focus on actionable information
- Use professional tone appropriate for enterprise IT environments

Current date: ${new Date().toISOString().split('T')[0]}`;

/**
 * Execute an OpenAI chat completion request
 * 
 * @param question - The user's question
 * @param options - Optional configuration (temperature, maxTokens, timeout)
 * @returns AiProviderResponse with answer and metadata
 */
export async function runOpenAi(
  question: string,
  options?: OpenAiOptions
): Promise<AiProviderResponse> {
  const model = env.OPENAI_MODEL || 'gpt-4.1-mini';
  const temperature = options?.temperature ?? env.OPENAI_TEMPERATURE ?? 0.7;
  const maxTokens = options?.maxTokens ?? env.OPENAI_MAX_TOKENS ?? 2000;
  const timeout = options?.timeout ?? env.OPENAI_TIMEOUT ?? 30000; // 30 second default timeout

  // Validate API key
  if (!env.OPENAI_API_KEY) {
    return {
      answer: 'OpenAI provider is selected but OPENAI_API_KEY is not configured. Please set the OPENAI_API_KEY environment variable.',
      metadata: {
        model,
        provider: 'openai',
      },
    };
  }

  // Initialize OpenAI client with timeout
  const openai = new OpenAI({
    apiKey: env.OPENAI_API_KEY,
    timeout,
    maxRetries: 2,
  });

  const startTime = Date.now();

  try {
    // Create chat completion request
    const completion = await openai.chat.completions.create({
      model,
      messages: [
        {
          role: 'system',
          content: SYSTEM_PROMPT,
        },
        {
          role: 'user',
          content: question,
        },
      ],
      temperature,
      max_tokens: maxTokens,
      top_p: 0.9,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    });

    const latencyMs = Date.now() - startTime;

    // Extract response
    const choice = completion.choices[0];
    const answer = choice?.message?.content || 'No response generated by OpenAI.';

    return {
      answer,
      raw: completion,
      metadata: {
        model,
        provider: 'openai',
        promptTokens: completion.usage?.prompt_tokens,
        completionTokens: completion.usage?.completion_tokens,
        totalTokens: completion.usage?.total_tokens,
        latencyMs,
      },
    };
  } catch (error) {
    const latencyMs = Date.now() - startTime;
    
    // Handle specific OpenAI errors
    if (error instanceof OpenAI.APIError) {
      console.error(`[OpenAI] API Error: ${error.status} - ${error.message}`);
      
      // Provide user-friendly error messages
      if (error.status === 401) {
        return {
          answer: 'OpenAI authentication failed. Please check your OPENAI_API_KEY is valid.',
          metadata: { model, provider: 'openai', latencyMs },
        };
      }
      if (error.status === 429) {
        return {
          answer: 'OpenAI rate limit exceeded. Please wait a moment and try again.',
          metadata: { model, provider: 'openai', latencyMs },
        };
      }
      if (error.status === 500) {
        return {
          answer: 'OpenAI server error. Please try again in a few moments.',
          metadata: { model, provider: 'openai', latencyMs },
        };
      }
      
      return {
        answer: `OpenAI error (${error.status}): ${error.message}`,
        metadata: { model, provider: 'openai', latencyMs },
      };
    }

    // Handle timeout errors
    if (error instanceof Error && error.name === 'TimeoutError') {
      console.error(`[OpenAI] Request timeout after ${timeout}ms`);
      return {
        answer: 'OpenAI request timed out. Please try again or use a simpler question.',
        metadata: { model, provider: 'openai', latencyMs },
      };
    }

    // Handle other errors
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error(`[OpenAI] Unexpected error: ${errorMessage}`);
    
    return {
      answer: `OpenAI request failed: ${errorMessage}`,
      metadata: { model, provider: 'openai', latencyMs },
    };
  }
}

/**
 * Validate OpenAI configuration
 * Returns true if OpenAI is properly configured
 */
export function isOpenAiConfigured(): boolean {
  return Boolean(env.OPENAI_API_KEY && env.AI_PROVIDER === 'openai');
}
